/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'username' : IDL.Text,
  'userId' : IDL.Vec(IDL.Nat8),
  'createdAt' : Time,
  'text' : IDL.Text,
  'chapterId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'createdAt' : Time,
  'comicId' : IDL.Nat,
  'number' : IDL.Nat,
  'pages' : IDL.Vec(IDL.Text),
});
export const Comic = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Text,
  'coverImage' : IDL.Text,
  'updatedAt' : Time,
  'viewCount' : IDL.Nat,
  'genres' : IDL.Vec(IDL.Nat),
  'artist' : IDL.Text,
});
export const Genre = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'avatarUrl' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Comment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createChapter' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [Chapter],
      [],
    ),
  'createComic' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Comic],
      [],
    ),
  'createGenre' : IDL.Func([IDL.Text], [Genre], []),
  'deleteChapter' : IDL.Func([IDL.Nat], [], []),
  'deleteComic' : IDL.Func([IDL.Nat], [], []),
  'deleteComment' : IDL.Func([IDL.Nat], [], []),
  'deleteGenre' : IDL.Func([IDL.Nat], [], []),
  'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'getAllComics' : IDL.Func([], [IDL.Vec(Comic)], ['query']),
  'getAllGenres' : IDL.Func([], [IDL.Vec(Genre)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChapterById' : IDL.Func([IDL.Nat], [Chapter], ['query']),
  'getChaptersByComicId' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
  'getComicById' : IDL.Func([IDL.Nat], [Comic], ['query']),
  'getComics' : IDL.Func(
      [
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Vec(Comic)],
      ['query'],
    ),
  'getCommentsByChapterId' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getLatestUpdatedComics' : IDL.Func([IDL.Nat], [IDL.Vec(Comic)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grabComicPages' : IDL.Func([IDL.Text], [IDL.Text], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateChapter' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
      [Chapter],
      [],
    ),
  'updateComic' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Nat),
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [Comic],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'username' : IDL.Text,
    'userId' : IDL.Vec(IDL.Nat8),
    'createdAt' : Time,
    'text' : IDL.Text,
    'chapterId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'createdAt' : Time,
    'comicId' : IDL.Nat,
    'number' : IDL.Nat,
    'pages' : IDL.Vec(IDL.Text),
  });
  const Comic = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Text,
    'coverImage' : IDL.Text,
    'updatedAt' : Time,
    'viewCount' : IDL.Nat,
    'genres' : IDL.Vec(IDL.Nat),
    'artist' : IDL.Text,
  });
  const Genre = IDL.Record({ 'id' : IDL.Nat, 'name' : IDL.Text });
  const UserProfile = IDL.Record({
    'username' : IDL.Text,
    'avatarUrl' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Comment], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createChapter' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [Chapter],
        [],
      ),
    'createComic' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Comic],
        [],
      ),
    'createGenre' : IDL.Func([IDL.Text], [Genre], []),
    'deleteChapter' : IDL.Func([IDL.Nat], [], []),
    'deleteComic' : IDL.Func([IDL.Nat], [], []),
    'deleteComment' : IDL.Func([IDL.Nat], [], []),
    'deleteGenre' : IDL.Func([IDL.Nat], [], []),
    'getAllChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'getAllComics' : IDL.Func([], [IDL.Vec(Comic)], ['query']),
    'getAllGenres' : IDL.Func([], [IDL.Vec(Genre)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChapterById' : IDL.Func([IDL.Nat], [Chapter], ['query']),
    'getChaptersByComicId' : IDL.Func([IDL.Nat], [IDL.Vec(Chapter)], ['query']),
    'getComicById' : IDL.Func([IDL.Nat], [Comic], ['query']),
    'getComics' : IDL.Func(
        [
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Vec(Comic)],
        ['query'],
      ),
    'getCommentsByChapterId' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Comment)],
        ['query'],
      ),
    'getLatestUpdatedComics' : IDL.Func([IDL.Nat], [IDL.Vec(Comic)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grabComicPages' : IDL.Func([IDL.Text], [IDL.Text], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateChapter' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Text, IDL.Vec(IDL.Text)],
        [Chapter],
        [],
      ),
    'updateComic' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Nat),
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [Comic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };