/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'title' : string,
  'createdAt' : Time,
  'comicId' : bigint,
  'number' : bigint,
  'pages' : Array<string>,
}
export interface Comic {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'createdAt' : Time,
  'type' : string,
  'description' : string,
  'author' : string,
  'coverImage' : string,
  'updatedAt' : Time,
  'viewCount' : bigint,
  'genres' : Array<bigint>,
  'artist' : string,
}
export interface Comment {
  'id' : bigint,
  'username' : string,
  'userId' : Uint8Array,
  'createdAt' : Time,
  'text' : string,
  'chapterId' : bigint,
}
export interface Genre { 'id' : bigint, 'name' : string }
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'username' : string, 'avatarUrl' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string, string], Comment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createChapter' : ActorMethod<
    [bigint, bigint, string, Array<string>],
    Chapter
  >,
  'createComic' : ActorMethod<
    [string, string, string, string, Array<bigint>, string, string, string],
    Comic
  >,
  'createGenre' : ActorMethod<[string], Genre>,
  'deleteChapter' : ActorMethod<[bigint], undefined>,
  'deleteComic' : ActorMethod<[bigint], undefined>,
  'deleteComment' : ActorMethod<[bigint], undefined>,
  'deleteGenre' : ActorMethod<[bigint], undefined>,
  'getAllChapters' : ActorMethod<[], Array<Chapter>>,
  'getAllComics' : ActorMethod<[], Array<Comic>>,
  'getAllGenres' : ActorMethod<[], Array<Genre>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChapterById' : ActorMethod<[bigint], Chapter>,
  'getChaptersByComicId' : ActorMethod<[bigint], Array<Chapter>>,
  'getComicById' : ActorMethod<[bigint], Comic>,
  'getComics' : ActorMethod<
    [[] | [bigint], [] | [string], [] | [string], [] | [string]],
    Array<Comic>
  >,
  'getCommentsByChapterId' : ActorMethod<[bigint], Array<Comment>>,
  'getLatestUpdatedComics' : ActorMethod<[bigint], Array<Comic>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grabComicPages' : ActorMethod<[string], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateChapter' : ActorMethod<
    [bigint, bigint, string, Array<string>],
    Chapter
  >,
  'updateComic' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      Array<bigint>,
      string,
      string,
      string,
    ],
    Comic
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];